version: "3.9"

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
  app:
    depends_on:
      - db
    image: task5
    ports:
      - "8181:8080"
volumes:
  db-data: {}
